CREATE TABLE Invited (id_event int4 NOT NULL, id_i_user int4 NOT NULL, attended bool NOT NULL, PRIMARY KEY (id_event, id_i_user));
CREATE TABLE Event (e_id  SERIAL NOT NULL, descript varchar(255) NOT NULL, id_founder int4 NOT NULL, PRIMARY KEY (e_id));
CREATE TABLE Friends (person_id int4 NOT NULL, friend_id int4 NOT NULL, PRIMARY KEY (person_id, friend_id));
CREATE TABLE Users (u_id  SERIAL NOT NULL, PRIMARY KEY (u_id));
ALTER TABLE Invited ADD CONSTRAINT FKInvited634451 FOREIGN KEY (id_event) REFERENCES Event (e_id) ON DELETE CASCADE;
ALTER TABLE Invited ADD CONSTRAINT FKInvited563501 FOREIGN KEY (id_i_user) REFERENCES Users (u_id) ON DELETE CASCADE;
ALTER TABLE Event ADD CONSTRAINT FKEvent342052 FOREIGN KEY (id_founder) REFERENCES Users (u_id) ON DELETE CASCADE;
ALTER TABLE Friends ADD CONSTRAINT FKFriends869808 FOREIGN KEY (friend_id) REFERENCES Users (u_id) ON DELETE CASCADE;
ALTER TABLE Friends ADD CONSTRAINT FKFriends354266 FOREIGN KEY (person_id) REFERENCES Users (u_id) ON DELETE CASCADE;